api/urls.py
from django.conf import settings
from django.urls import path, include
from rest_framework import routers

from .views import (
    ConstructorStandingView, DriverStandingView, RaceResultView,
)

router = routers.DefaultRouter()
router.register(r'race_result', RaceResultView)
router.register(r'driver_standing', DriverStandingView)
router.register(r'constructor_standing', ConstructorStandingView)

app_name = "api"
urlpatterns = [
    path("", include(router.urls)),
]

if settings.DEBUG:
    from .views import (
        SyncConstructorStandingViews, SyncDriverStandingsView, SyncRaceResultsView
    )
    urlpatterns += [
        path("sync_constructor_standings/", SyncConstructorStandingViews.as_view()),
        path("sync_driver_standings/", SyncDriverStandingsView.as_view()),
        path("sync_race_results/", SyncRaceResultsView.as_view()),
    ]

app/urls.py
from django.urls import path

from app.views import IndexView, DriverStandingView, ConstructorStandingView, RaceResultView

app_name = "app"
urlpatterns = [
    path('', IndexView.as_view(), name='top'),
    path('driver_standing', DriverStandingView.as_view(), name='driver_standing'),
    path('constructor_standing', ConstructorStandingView.as_view(), name='constructor_standing'),
    path('race_result', RaceResultView.as_view(), name='race_result'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/models/constructor_standing.py
from django.db import models


class ConstructorStandingModel(models.Model):
    constructor = models.CharField(max_length=50)
    position = models.IntegerField()
    points = models.FloatField()
    season = models.IntegerField()

    def __str__(self) -> str:
        return self.constructor

    class Meta:
        db_table = 'constructor_standings'

core/models/driver_standing.py
from django.db import models


class DriverStandingModel(models.Model):
    driver = models.CharField(max_length=50)
    position = models.IntegerField()
    nationality = models.CharField(max_length=50)
    team = models.CharField(max_length=50, null=True, blank=True, default=None)
    points = models.FloatField()
    season = models.IntegerField()

    def __str__(self) -> str:
        return self.driver

    class Meta:
        db_table = 'driver_standings'

core/forms/constructor_standing.py
from django import forms

from core.models import ConstructorStandingModel


class ConstructorStandingForm(forms.ModelForm):
    class Meta:
        model = ConstructorStandingModel
        fields = '__all__'

core/forms/driver_standing.py
from django import forms

from core.models import DriverStandingModel


class DriverStandingForm(forms.ModelForm):
    class Meta:
        model = DriverStandingModel
        fields = '__all__'

api/views/constructor_standing.py
from rest_framework import viewsets

from core.filters import ConstructorStandingFilter
from core.models import ConstructorStandingModel
from core.serializers import ConstructorStandingSerializer


class ConstructorStandingView(viewsets.ModelViewSet):
    """Constructor Standing API"""

    queryset = ConstructorStandingModel.objects.all()
    serializer_class = ConstructorStandingSerializer
    filterset_class = ConstructorStandingFilter
    ordering_fields = '__all__'

api/views/driver_standing.py
from rest_framework import viewsets

from core.filters import DriverStandingFilter
from core.models import DriverStandingModel
from core.serializers import DriverStandingSerializer


class DriverStandingView(viewsets.ModelViewSet):
    """Driver Standing API"""

    queryset = DriverStandingModel.objects.all()
    serializer_class = DriverStandingSerializer
    filterset_class = DriverStandingFilter
    ordering_fields = '__all__'

api/views/race_result.py
from rest_framework import viewsets

from core.filters import RaceResultFilter
from core.models import RaceResultModel
from core.serializers import RaceResultSerializer


class RaceResultView(viewsets.ModelViewSet):
    """Race Result API"""

    queryset = RaceResultModel.objects.all()
    serializer_class = RaceResultSerializer
    filterset_class = RaceResultFilter
    ordering_fields = '__all__'

app/views/constructor_standing.py
from datetime import datetime
from django.views.generic import View
from django.shortcuts import render

from core.models import ConstructorStandingModel


class ConstructorStandingView(View):
    """初期表示用のビュー"""

    def get(self, request, *args, **kwargs):
        """get関数"""
        default_year = request.GET.get('year', datetime.now().year)
        constructor_standing = \
            ConstructorStandingModel.objects.filter(season=default_year).order_by('position').all()
        years = []
        for year in ConstructorStandingModel.objects.values('season').order_by('-season').distinct():
            years.append(str(year['season']))
        context = {
            'rankings': constructor_standing,
            'default_year': default_year,
            'years': years,
        }
        return render(request, 'app/constructor_standing.html', context=context)

app/views/driver_standing.py
from datetime import datetime
from django.views.generic import View
from django.shortcuts import render

from core.models import DriverStandingModel


class DriverStandingView(View):
    """初期表示用のビュー"""

    def get(self, request, *args, **kwargs):
        """get関数"""
        # 現在の年度を取得
        default_year = request.GET.get('year', datetime.now().year)
        driver_standing = \
            DriverStandingModel.objects.filter(season=default_year).order_by('position').all()
        years = []
        for year in DriverStandingModel.objects.values('season').order_by('-season').distinct():
            years.append(str(year['season']))
        context = {
            'rankings': driver_standing,
            'default_year': default_year,
            'years': years,
        }
        return render(request, 'app/driver_standing.html', context=context)

app/views/race_result.py
from datetime import datetime
from django.views.generic import View
from django.shortcuts import render

from core.models import RaceResultModel


class RaceResultView(View):
    """初期表示用のビュー"""

    def get(self, request, *args, **kwargs):
        """get関数"""
        # 現在の年度を取得
        default_year = request.GET.get('year', datetime.now().year)
        race_results = RaceResultModel.objects.filter(season=default_year).order_by('-race_date').order_by('-season').all()
        years = []
        for year in RaceResultModel.objects.values('season').order_by('-season').distinct():
            years.append(str(year['season']))
        context = {
            'rankings': race_results,
            'default_year': default_year,
            'years': years,
        }
        return render(request, 'app/race_result.html', context=context)

templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <title>F1 Ranking</title>
</head>
<body>
    <div id="splash">
        <div id="splash_text"></div>
    </div>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="/" class="navbar-brand">
                <!-- TODO: Logo is Pending -->
                <!-- <img src="{% static 'myapp/images/logo.jpg' %}" alt="Logo" width="50" height="50"> -->
            </a>
            <ul class="navbar-nav">
                <li class=""nav-item mr-3>
                    <a href="{% url 'app:top' %}" class="nav-link nav-color">ホーム</a>
                </li>
                <li class=""nav-item mr-3>
                    <a href="{% url 'app:race_result' %}" class="nav-link nav-color">レース</a>
                </li>
                <li class=""nav-item mr-3>
                    <a href="{% url 'app:driver_standing' %}" class="nav-link nav-color">ドライバー</a>
                </li>
                <li class=""nav-item mr-3>
                    <a href="{% url 'app:constructor_standing' %}" class="nav-link nav-color">コンストラクター</a>
                </li>
            </ul>
        </div>
    </nav>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <!-- TODO: Header is Pending -->
    {% comment %} <footer class="py-4 bg-dark text-center"> {% endcomment %}
        {% comment %} <small class="text-white">&copy; 2024 Hiroyuki Nakano</small> {% endcomment %}
    {% comment %} </footer> {% endcomment %}
    {% block extra_js %}
    {% endblock %}
</body>
</html>

templates/app/constructor_standing.html
{% extends 'app/base.html' %}

{% block content %}

<h2>2024年 コンストラクターランキング</h2>
<form method="GET">
    <select name="year" id="year">
        {% for year in years %}
            {% if year == default_year %}
                <option value="{{ year }}" selected>{{ year }}年</option>
            {% else %}
                <option value="{{ year }}">{{ year }}年</option>
            {% endif %}
        {% endfor %}
    </select>
    <button type="submit">選択</button>
</form>
<table>
    <thead>
        <tr>
            <th>Pos</th>
            <th>Team</th>
            <th>Pts</th>
        </tr>
    </thead>
    <tbody>
        {% for ranking in rankings %}
            <tr>
                <td>{{ ranking.position }}</td>
                <td>{{ ranking.constructor }}</td>
                <td>{{ ranking.points }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock%}

templates/app/driver_standing.html
{% extends 'app/base.html' %}

{% block content %}

<h2>2024年 ドライバーランキング</h2>
<form method="GET">
    <select name="year" id="year">
        {% for year in years %}
            {% if year == default_year %}
                <option value="{{ year }}" selected>{{ year }}年</option>
            {% else %}
                <option value="{{ year }}">{{ year }}年</option>
            {% endif %}
        {% endfor %}
    </select>
    <button type="submit">選択</button>
</form>
<table>
    <thead>
        <tr>
            <th>Pos</th>
            <th>Driver</th>
            <th>Nationality</th>
            <th>Car</th>
            <th>Pts</th>
        </tr>
    </thead>
    <tbody>
        {% for ranking in rankings %}
            <tr>
                <td>{{ ranking.position }}</td>
                <td>{{ ranking.driver }}</td>
                <td>{{ ranking.nationality }}</td>
                <td>{{ ranking.team }}</td>
                <td>{{ ranking.points }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock%}

templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

<h2>2024年 レースランキング</h2>
<table>
    <thead>
        <tr>
            <th>Grand Prix</th>
            <th>Date</th>
            <th>Winner</th>
            <th>Car</th>
            <th>Laps</th>
            <th>Time</th>
        </tr>
    </thead>
    <tbody>
        {% for race_result in race_results %}
            <tr>
                <td>{{ race_result.grand_prix }}</td>
                <td>{{ race_result.race_date }}</td>
                <td>{{ race_result.winner }}</td>
                <td>{{ race_result.car }}</td>
                <td>{{ race_result.laps }}</td>
                <td>{{ race_result.race_time }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h2>2024年 ドライバーランキング</h2>
<table>
    <thead>
        <tr>
            <th>Pos</th>
            <th>Driver</th>
            <th>Nationality</th>
            <th>Car</th>
            <th>Pts</th>
        </tr>
    </thead>
    <tbody>
        {% for driver_standing in driver_standings %}
            <tr>
                <td>{{ driver_standing.position }}</td>
                <td>{{ driver_standing.driver }}</td>
                <td>{{ driver_standing.nationality }}</td>
                <td>{{ driver_standing.team }}</td>
                <td>{{ driver_standing.points }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h2>2024年 コンストラクターランキング</h2>
<table>
    <thead>
        <tr>
            <th>Pos</th>
            <th>Team</th>
            <th>Pts</th>
        </tr>
    </thead>
    <tbody>
        {% for constructor_standing in constructor_standings %}
            <tr>
                <td>{{ constructor_standing.position }}</td>
                <td>{{ constructor_standing.constructor }}</td>
                <td>{{ constructor_standing.points }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock%}

templates/app/race_result.html
{% extends 'app/base.html' %}

{% block content %}

<h2>2024年 レースランキング</h2>
<form method="GET">
    <select name="year" id="year">
        {% for year in years %}
            {% if year == default_year %}
                <option value="{{ year }}" selected>{{ year }}年</option>
            {% else %}
                <option value="{{ year }}">{{ year }}年</option>
            {% endif %}
        {% endfor %}
    </select>
    <button type="submit">選択</button>
</form>
<table>
    <thead>
        <tr>
            <th>Grand Prix</th>
            <th>Date</th>
            <th>Winner</th>
            <th>Car</th>
            <th>Laps</th>
            <th>Time</th>
        </tr>
    </thead>
    <tbody>
        {% for ranking in rankings %}
            <tr>
                <td>{{ ranking.grand_prix }}</td>
                <td>{{ ranking.race_date }}</td>
                <td>{{ ranking.winner }}</td>
                <td>{{ ranking.car }}</td>
                <td>{{ ranking.laps }}</td>
                <td>{{ ranking.race_time }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">データがありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock%}